version: "3.9"

services: # mariadb para dev
  mariadb:
    image: mariadb:latest
    container_name: mariadb_estudos
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
   name: mariadb_dev
